apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  simplenginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /dev/stderr error;

    events {
        worker_connections 1024;
    }

    http {
        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        server {
            listen        80 proxy_protocol;
            server_name   _;

            access_log /dev/stdout combined;

            location / {
                return 200 "Everything is OK.\n";
            }
        }

        server {
            listen       443 ssl;
            server_name  pttg-income-proving-api.pt-i-dev.svc.cluster.local;

            access_log /dev/stdout combined;

            ssl_certificate     /etc/nginx/secrets/pttg-income-proving-api.crt;
            ssl_certificate_key /etc/nginx/secrets/pttg-income-proving-api.key;
            ssl_protocols  TLSv1.2;
            ssl_ciphers    HIGH:!aNULL:!MD5;
            ssl_session_cache shared:SSL:20m;
            ssl_session_timeout 4h;
            ssl_session_tickets on;

            location / {
                proxy_pass http://localhost:8080;
            }
            location /nginx_status {
              stub_status;
              access_log   off;
              allow 10.200.0.0/16;
              allow 127.0.0.1/32;
              deny all;
            }
        }
    }
