apiVersion: v1
kind: ReplicationController
metadata:
  name: pttg-income-proving-api
  labels:
    name: pttg-income-proving-api
    version: ${pt-income-version}
spec:
  replicas: 1
  selector:
    name: pttg-income-proving-api
  template:
    metadata:
      labels:
        name: pttg-income-proving-api
        version: ${pt-income-version}
    spec:
      containers:
      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-income-proving-api.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-income-proving-api,fmt=cert
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx:v0.0.1
        env:
          - name: NGINX_CONFIG_FILE
            value: /etc/nginx/conf/simplenginx.conf
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/conf
            readOnly: true
        ports:
          - name: https
            containerPort: 443
          - name: proxyhttp
            containerPort: 80
      - name: pttg-income-proving-api
        image: quay.io/ukhomeofficedigital/pttg-income-proving-api:${ pt-income-version }
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        ports:
          - name: http
            containerPort: 8080
        imagePullPolicy: Always
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: nginx-config
        configMap:
          name: nginx-config
