apiVersion: v1
kind: ReplicationController
metadata:
  name: pttg-income-proving-api
  labels:
    name: pttg-income-proving-api
    version: ${pt-income-version}
spec:
  replicas: 1
  selector:
    name: pttg-income-proving-api
  template:
    metadata:
      labels:
        name: pttg-income-proving-api
        version: ${pt-income-version}
    spec:
      containers:
      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-income-proving-api.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-income-proving-api,fmt=cert
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.1.5
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOAD_BALANCER_CIDR
            value: '10.50.0.0/22'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/pttg-income-proving-api.crt
          - name: SERVER_KEY
            value: /etc/nginx/secrets/pttg-income-proving-api.key
          - name: LOG_FORMAT_NAME
            value: text
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 443
      - name: pttg-income-proving-api
        image: quay.io/ukhomeofficedigital/pttg-income-proving-api:${ pt-income-version }
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        ports:
          - name: http
            containerPort: 8081
        imagePullPolicy: Always
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
