---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-ip-api-testing
  name: pttg-ip-api-testing
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: https
  selector:
    name: pttg-ip-api-testing
