---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-ip-api
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-ip-api
  template:
    metadata:
      labels:
        name: pttg-ip-api
        version: {{.VERSION}}
    spec:
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-ip-api.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-ip-api,fmt=bundle
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.5.1
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '9000'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/pttg-ip-api-bundle.pem
          - name: SERVER_KEY
            value: /etc/nginx/secrets/pttg-ip-api-key.pem
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 443
          - name: http
            containerPort: 80
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v1.2.7
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_DISCOVERY_URL
          - name: PROXY_REDIRECTION_URL
            valueFrom:
              configMapKeyRef:
                name: endpoint-config
                key: PROXY_REDIRECTION_URL
        args:
          - --config=/etc/secrets/keycloak-api-secret.yaml
          - --client-id=pttg-fs-{{.ENVIRONMENT}}
          - --listen=127.0.0.1:9000
          - --log-requests=true
          - --json-logging=true
          - --upstream-url=http://127.0.0.1:8080
          - --no-redirects=true
          - --cors-origins='*'
          - --resource=uri=/healthz|white-listed=true
          - --resource=uri=/|methods=GET|roles=pttg-user
          - --secure-cookie=true
          - --verbose
        imagePullPolicy: Always
        ports:
          - name: keycloak-http
            containerPort: 9000
        volumeMounts:
        - name: keycloak-api-secret
          mountPath: /etc/secrets
          readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
      - name: pttg-ip-api
        image: quay.io/ukhomeofficedigital/pttg-ip-api:{{.VERSION}}
        env:
          - name: JAVA_OPTS
            value: "-Xms150m -Xmx250m"
          - name: MONGODB_SERVICE
            value: 'pttg-mongodb'
          - name: SERVER_PORT
            value: '8080'
          - name: HRMC_SERVICE_URL
            value: "http://pttg-ip-hmrc"
        resources:
          limits:
            cpu: 1700m
            memory: 612Mi
          requests:
            cpu: 100m
            memory: 484Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
        imagePullPolicy: Always
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: keycloak-api-secret
        secret:
          secretName: keycloak-api-secret