---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-ip-api
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-ip-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-ip-api
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      initContainers:
        
        - name: get-ca-certs
          image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.2
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-ip-api.${KUBE_NAMESPACE}.svc.cluster.local
            - --onetime=true
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        
        - name: create-truststore
          image: quay.io/ukhomeofficedigital/pttg-docker-openjdk8:latest
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          volumeMounts:
            - name: store
              mountPath: /store
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -alias servercert -file /etc/ssl/certs/ca-bundle.crt -keystore /store/truststore.jks -noprompt -storepass changeit"]
      
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/pttg-cfssl-sidekick:build-6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-ip-api.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
  
        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.6
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              memory: "100Mi"
              cpu: 100m
            requests:
              memory: "50Mi"
              cpu: 100m
          env:
            - name: PROXY_SERVICE_HOST
              value: '127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '8080'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: HTTPS_REDIRECT
              value: 'FALSE'
            - name: SERVER_CERT
              value: /etc/nginx/secrets/pttg-ip-api-bundle.pem
            - name: SERVER_KEY
              value: /etc/nginx/secrets/pttg-ip-api-key.pem
            - name: ADD_NGINX_SERVER_CFG
              value: 'gzip off;'
            - name: BASIC_AUTH
              value: /etc/nginx/service-secrets/.htpasswd_1
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: secrets
              mountPath: /etc/nginx/secrets
              readOnly: true
            - name: service-secrets
              mountPath: /etc/nginx/service-secrets
              readOnly: true
          ports:
            - name: https
              containerPort: 10443
        
        - name: pttg-ip-api
          image: quay.io/ukhomeofficedigital/pttg-ip-api:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              runAsNonRoot: true
              drop:
                - SETUID
                - SETGID
          env:
            - name: JAVA_OPTS
              value: '-Xms150m -Xmx250m -Djavax.net.ssl.trustStore=/store/truststore.jks'
            - name: JDK_TRUST_FILE
              value: '/store/truststore.jks'
            - name: SERVER_PORT
              value: '8080'
            - name: ENDPOINTS_INFO_ENABLED
              value: 'false'
            - name: HMRC_SERVICE_AUTH
              valueFrom:
                secretKeyRef:
                  name: pttg-hmrc-service-secrets
                  key: pttg_ip_api
            - name: HRMC_SERVICE_URL
              value: "https://pttg-ip-hmrc.pt-i-{{.ENVIRONMENT}}.svc.cluster.local"
            - name: HMRC_SERVICE_RETRY_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: rest-retry-config
                  key: HMRC_SERVICE_RETRY_ATTEMPTS
            - name: HMRC_SERVICE_RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  name: rest-retry-config
                  key: HMRC_SERVICE_RETRY_DELAY
            - name: AUDIT_SERVICE_AUTH
              valueFrom:
                secretKeyRef:
                  name: pttg-audit-service-secrets
                  key: pttg_ip_api
            - name: PTTG_AUDIT_URL
              value: 'https://pttg-ip-audit.pt-i-{{.ENVIRONMENT}}.svc.cluster.local'
            - name: AUDITING_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUDITING_DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUDIT_SERVICE_RETRY_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: rest-retry-config
                  key: AUDIT_SERVICE_RETRY_ATTEMPTS
            - name: AUDIT_SERVICE_RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  name: rest-retry-config
                  key: AUDIT_SERVICE_RETRY_DELAY
          resources:
            limits:
              cpu: 1600m
              memory: 612Mi
            requests:
              cpu: 100m
              memory: 484Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /store
              name: store
              readOnly: true
      volumes:
        - name: store
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
        - name: secrets
          emptyDir:
            medium: "Memory"
        - name: service-secrets
          secret:
            secretName: pttg-ip-api-service-secrets
        - name: keycloak-api-secret
          secret:
            secretName: keycloak-api-secret
