apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pttg-pm-cleardown
  labels:
    version: {{.VERSION}}
    application: pttg-ip-api
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pttg-pm-cleardown
              image: quay.io/ukhomeofficedigital/openjdk11
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              command: ["kubectl delete pods --all -n ${IP_NAMESPACE}"]
              env:
                - name: IP_NAMESPACE
                  value: 'pttg-ip-{{.ENVIRONMENT}}'
