apiVersion: batch/v1
kind: CronJob
metadata:
  name: pttg-pm-cleardown
  labels:
    version: {{.VERSION}}
    application: pttg-ip-api
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pttg-pm-cleardown
              image: quay.io/ukhomeofficedigital/openjdk11
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              imagePullPolicy: IfNotPresent
              command:
                - "kubectl delete pods --all -n pttg-ip-dev"
          restartPolicy: OnFailure